server:
  port: 8001
spring:
  application:
    name: turbine
  rabbitmq:
    addresses: 101.200.55.76
    port: 5672
    virtual-host: LoadStar_Dev
turbine:
  app-config: user-service
  combine-host-port:
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://registry:9001/eureka/