server:
  port: 8001
spring:
  application:
    name: turbine
turbine:
  app-config: user-service
  combine-host-port: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://registry:9001/eureka/