app:
  id: Loadstar
spring:
  profiles:
    active: dev
  application:
    name: auth-service
#  zipkin:
#    enabled: true
#    base-url: http://101.200.55.76:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
#      probability: 1.0
  redis:
    host: ${Redis_Host:'101.200.55.76'}
    port: ${Redis_Port:'6379'}
    password: ${Redis_Pwd:'123456!'}
server:
  port: 9081
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

apollo:
  bootstrap:
    enabled: true
