app:
  id: Loadstar
spring:
  application:
    name: auth-service
  zipkin:
    enabled: true
    base-url: http://loadstar.top:9411
logging:
  config: classpath:log-config.xml
  level:
    root: WARN
    com:
      ciel:
        pocket: INFO