spring:
  datasource:
    url: jdbc:mysql://rm-bp1uc95ps57o9b7t79o.mysql.rds.aliyuncs.com:3306/LoadStar_Account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: loadstar
    password: loadstar123!
    type: com.alibaba.druid.pool.DruidDataSource
global:
  auth:
    prefix: LoadStarAuth_
apollo:
  meta: http://10.0.75.2:7094
logging:
  config: classpath:log-config.xml