spring:
  profiles:
    active: dev
  application:
    name: auth-service
  zipkin:
    enabled: true
    base-url: http://101.200.55.76:9411
  sleuth:
    sampler:
      percentage: 1.0
      probability: 1.0
server:
  port: 9081
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/