version: '3'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper
  
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://101.200.55.76:9093
      # KAFKA_ADVERTISED_HOST_NAME: 101.200.55.76
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 4
    depends_on:
      - zoo1
    container_name: kafka1

  kafkamanager:
    image: sheepkiller/kafka-manager
    ports:
      - "9090:9000"
    environment:
      ZK_HOSTS: zoo1:2181
      APPLICATION_SECRET: "letmein"
    depends_on:
      - zoo1
    container_name: kafka-manager