version: "3"
services:
  gateway:
    image: cielqian/loadstar-gateway
    restart: always
    ports:
      - 9080:9080
    volumes:
      - /usr/dock/loadstar/logs:/logs
    mem_limit: 256M

  auth-service:
    image: cielqian/loadstar-auth-service:1.0.1
    restart: always
    ports:
      - 9081:9081
    volumes:
      - /usr/dock/loadstar/logs/auth-service:/logs
    mem_limit: 256M


  user-service:
    image: cielqian/loadstar-user-service:1.0.1
    restart: always
    ports:
      - 9082:9082
    volumes:
      - /usr/dock/loadstar/logs/user-service:/logs
    mem_limit: 256M

  link-service:
    image: cielqian/loadstar-link-service:1.0.1
    restart: always
    ports:
      - 9083:9083
    volumes:
      - /usr/dock/loadstar/logs/link-service:/logs
    mem_limit: 256M

#  web-container:
#    image: cielqian/loadstar-web
#    restart: always
#    volumes:
#      - /usr/dock/loadstar/config/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /usr/dock/loadstar/config/nginx/cert:/etc/nginx/cert
#    ports:
#      - 81:80
#      - 443:443
#      - 80:80