spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 9080
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
    enabled: true


zuul:
#  SendErrorFilter:
#    error:
#      disable: true
  ignored-services: '*'
  routes:
    auth:
      path: /auth-service/**
      sensitiveHeaders:
      serviceId: auth-service

    user:
      path: /user-service/**
      sensitiveHeaders:
      serviceId: user-service

    link:
      path: /link-service/**
      sensitiveHeaders:
      serviceId: link-service