ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
    enabled: true
zuul:
#  SendErrorFilter:
#    error:
#      disable: true
  ignored-services: '*'
  routes:
    auth:
      path: /auth-service/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: auth-service
    user:
      path: /user-service/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: user-service

    link:
      path: /link-service/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: link-service
security:
  oauth2:
    resource:
      jwt:
        key-value: loadstar
logback:
  access:
    config: classpath:logback-access.xml