spring:
  datasource:
    url: jdbc:mysql://rm-bp1uc95ps57o9b7t79o.mysql.rds.aliyuncs.com:3306/LoadStar_Link?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: loadstar
    password: loadstar123!
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        namespace: 898be752-5f5b-4dcb-b8e9-3255d3aa1fbb
logging:
  config: classpath:log-config.xml
  level:
    root: INFO