spring:
  profiles:
    active: dev
  application:
    name: link-service
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
#  zipkin:
#    enabled: true
#    base-url: http://101.200.55.76:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
#      probability: 1.0
security:
  oauth2:
    client:
      scope: server
      client-id: user-service
      grant-type: client_credentials
      accessTokenUri: http://gateway:9080/auth-service/oauth/token
      client-secret: POCKET-USER-SERVICE
    resource:
      user-info-uri: http://gateway:9080/auth-service/api/users/current
      prefer-token-info: false
server:
  port: 9083
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
ribbon:
  eager-load:
    enabled: true

mybatis:
    type-aliases-package: com.ciel.pocket.link.model,com.ciel.pocket.link.dto.output
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.ciel.pocket.link.infrastructure.mapper.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
