spring:
  zipkin:
    enabled: false
#    base-url: http://loadstar.top:9411
ribbon:
  eager-load:
    enabled: true
logging:
  config: classpath:log-config.xml
  level:
    root: WARN
    com:
      ciel:
        pocket: INFO