spring:
  datasource:
    url: jdbc:mysql://rm-bp1uc95ps57o9b7t79o.mysql.rds.aliyuncs.com:3306/LoadStar_Link?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: loadstar
    password: loadstar123!
    type: com.alibaba.druid.pool.DruidDataSource
loadstar:
  kafka:
    topic:
      UserAccountEvent: tfjmqdc9-UserAccountEvent
      linkThumbnail: LoadStar_Link_Thumbnail
logging:
  config: classpath:log-config.xml
  level:
    root: WARN
    com:
      ciel: INFO