spring:
  datasource:
    url: jdbc:mysql://101.200.55.76:3306/LoadStar_Link?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456!
    type: com.alibaba.druid.pool.DruidDataSource
loadstar:
  kafka:
    topic:
      createFolder: LoadStar_Create_Folder
      linkThumbnail: LoadStar_Link_Thumbnail
logging:
  config: classpath:log-config.xml
