spring:
  profiles:
    active: dev
  application:
    name: link-service
  zipkin:
    enabled: false
#    base-url: http://loadstar.top:9411
  kafka:
    bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: link-service-${spring.profiles.active}
      auto-offset-reset: latest
      enable-auto-commit: true
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="tfjmqdc9" password="mAR70SmzqRQGffklsv7cZ7ne4Yl83mEC";
  redis:
    host: redis-17961.c81.us-east-1-2.ec2.cloud.redislabs.com
    port: 17961
    password: KlUltGrKHAOlXGLxc1jjfjqpXtgAxrZj
  cloud:
    nacos:
      discovery:
        server-addr: loadstar.top:8848
#          username: BGA7j8ovyi
#          password: 3Ay9gmKnCMsLFiWxRGqb6h4

#  sleuth:
#    sampler:
#      percentage: 1.0
#      probability: 1.0
#security:
#  oauth2:
#    client:
#      scope: server
#      client-id: user-service
#      grant-type: client_credentials
#      accessTokenUri: http://gateway:9080/auth-service/oauth/token
#      client-secret: POCKET-USER-SERVICE
#    resource:
#      user-info-uri: http://gateway:9080/auth-service/api/users/current
#      prefer-token-info: false
server:
  port: 9083
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: link-service
ribbon:
  eager-load:
    enabled: true
loadstar:
  es:
    clustername: Loadstar
    index: loadstar
    hosts:
      -
        ip: loadstar-6473901552.us-west-2.bonsaisearch.net
        port: 80
        schema: http
        username: BGA7j8ovyi
        password: 3Ay9gmKnCMsLFiWxRGqb6h4
  kafka:
    topic:
      UserAccountEvent: tfjmqdc9-UserAccountEvent
      LinkEvent: tfjmqdc9-LinkEvent
  zimg: http://loadstar.top:4869




