spring:
  zipkin:
    enabled: false
    base-url: http://loadstar.top:9411
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eager-load:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
mybatis-plus:
  mapper-locations: classpath*:/repository/*.xml
  typeAliasesPackage: com.ciel.loadstar.user.entity,com.ciel.loadstar.user.dto.output
  typeEnumsPackage: com.ciel.loadstar.user.infrastructure.enums
  global-config:
    db-config:
      id-type: id_worker
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'