spring:
  datasource:
    druid:
      url: jdbc:mysql://101.200.55.76:3306/LoadStar_User_Dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456!

  kafka:
    producer:
      bootstrap-servers: 101.200.55.76:9093
#  rabbitmq:
#    addresses: 101.200.55.76
#    port: 5672
#    virtual-host: LoadStar_Dev
