spring:
  datasource:
    druid:
      url: jdbc:mysql://101.200.55.76:3306/LoadStar_User?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456!
loadstar:
  kafka:
    topic:
      createFolder: LoadStar_Create_Folder
#  rabbitmq:
#    addresses: 101.200.55.76
#    port: 5672
#    virtual-host: LoadStar
logging:
  config: classpath:log-config.xml