spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uc95ps57o9b7t79o.mysql.rds.aliyuncs.com:3306/LoadStar_User?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: loadstar
      password: loadstar123!
loadstar:
  kafka:
    topic:
      createFolder: LoadStar_Create_Folder
#  rabbitmq:
#    addresses: 101.200.55.76
#    port: 5672
#    virtual-host: LoadStar
logging:
  config: classpath:log-config.xml