spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uc95ps57o9b7t79o.mysql.rds.aliyuncs.com:3306/LoadStar_User?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: loadstar
      password: loadstar123!
  cloud:
    nacos:
      discovery:
        namespace: 898be752-5f5b-4dcb-b8e9-3255d3aa1fbb
logging:
  config: classpath:log-config.xml
  level:
    root: INFO