spring:
  zipkin:
    enabled: false
    base-url: http://loadstar.top:9411
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eager-load:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-enums-package: com.ciel.pocket.user.infrastructure.enums
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log-config.xml
  level:
    root: WARN
    com:
      ciel:
        pocket: INFO

