spring:
  application:
    name: registry
eureka:
  instance:
#    prefer-ip-address: true
    hostname: registry
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://registry:9001/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
server:
  port: 9001
