spring:
  application:
    name: registry
server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://registry:9001/eureka/
