version: '3'

services:
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://101.200.55.76:9093
      # KAFKA_ADVERTISED_HOST_NAME: 101.200.55.76
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 4
      KAFKA_JVM_PERFORMANCE_OPTS: " -Xmx256m -Xms256m"
    links:
      - zookeeper
    container_name: kafka1
    networks: 
      - default 
      - loadstar 

  kafkamanager:
    image: sheepkiller/kafka-manager
    ports:
      - "9090:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "letmein"
    links:
      - zookeeper
    container_name: kafka-manager
    networks: 
      - default 
      - loadstar 

networks:
  loadstar:
    external: true 