spring:
  datasource:
    url: jdbc:mysql://101.200.55.76:3306/LoadStar_Account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456!
    type: com.alibaba.druid.pool.DruidDataSource
global:
  auth:
    prefix: LoadStarAuth
apollo:
  meta: http://10.0.75.2:7094
logging:
  config: classpath:log-config.xml