spring:
  data:
    mongodb:
      host: 101.200.55.76
      database: pocket-auth
      port: 27137
  application:
    name: auth-service
  zipkin:
    enabled: true
    base-url: http://101.200.55.76:9411
  sleuth:
    sampler:
      percentage: 1.0
      probability: 1.0
server:
  port: 9081
eureka:
  client:
    service-url:
      defaultZone: http://registry:9001/eureka/
mongo:
  host: 101.200.55.76
  port: 27137
  database: pocket-auth